version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
        # AMQP protocol port
        - 5672:5672
        # HTTP management UI
        - 15672:15672
    volumes:
        - rabbitmq-svc:/var/lib/rabbitmq/
        - rabbitmq-svc:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=sectenzorg
      - RABBITMQ_DEFAULT_PASS=P@ssw0rd123!@#
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  rabbitmq-svc: